spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  application:
    name: ${APP_NAME}

app:
  data:
    number-of-customers: ${NUMBER_OF_CUSTOMERS}
    number-of-products: ${NUMBER_OF_PRODUCTS}
    number-of-orders: ${NUMBER_OF_ORDERS}



