spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:postgresql://host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  application:
    name: ${APP_NAME}
  sql:
    init:
      mode: never

server:
  port: ${PROD_SERVER_PORT}



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

